Override the visibility_copy_class so that we can force it to use ActiveFedora instead of an agnostic work type, and introduce a fix for the "NoMethodError: undefined method `title' for nil:NilClass"