Squashed commit of the following:
commit 1ed5f2936782131f67e52911cfdf91b297e538a0
Author: Samuel Klopsch <samuelklopsch@gmail.com>
Date:   Tue Mar 17 10:10:58 2026 -0600

    Change back to using visibility_copy_job

commit 0214cb5ca8a088b40b6a5984c2bbe043fef3ab5d
Author: Samuel Klopsch <samuelklopsch@gmail.com>
Date:   Wed Mar 4 09:59:35 2026 -0700

    Add log file directory for clamav

commit 973696fcdcf9240053894a7086d3e2d46fa40c82
Author: Samuel Klopsch <samuelklopsch@gmail.com>
Date:   Fri Feb 27 10:00:22 2026 -0700

    Cleanup comment in dockerignore

commit 35d979f128e998e19602f27b084673c27de398b5
Author: Samuel Klopsch <samuelklopsch@gmail.com>
Date:   Fri Feb 27 09:54:16 2026 -0700

    - Restructure Dockerfile into three stages: clamav-builder, builder, and runtime (hyrax-base) to reduce final image size and improve layer caching
    - Add directories to .dockerignore to exclude unnecessary files from build context
    - Add hyrax_search_service_patch.rb to stop deprecated warnings from filling the logs
    - Update work_uploads_handler.rb to fix undefined method 'title' for Nil:NilClass
    - Update comment in file_sets_controller.rb
    - Update Gemfile/Gemfile.lock with new/updated gem dependencies
    - Switch from package-lock.json to .npmrc + yarn.lock (remove package-lock.json)
    - Update package.json to require yarn to build
    - Update hyrax.rb initializer configuration to fix a runtime error

commit 6e8d6d12c50f92a8767213bf60dee1b92e73248e
Author: Samuel Klopsch <samuelklopsch@gmail.com>
Date:   Fri Feb 20 18:01:29 2026 -0700

    Override the visibility_copy_class so that we can force it to use ActiveFedora instead of an agnostic work type, and introduce a fix for the "NoMethodError: undefined method `title' for nil:NilClass"